
  #   配置次路径后，所有的资源访问路径都会加上/app前缀
#  context-path: /app

security:
  user:
    password: weak
    name: foo
# actuator 配置
management:
  port: 54001




# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
server:
  port: 8090

---
spring:
  profiles: dev

---
# 测试环境配置
spring:
  profiles: test
#  datasource:
#    url: jdbc:mysql://192.168.0.12:3306/

---
# 生产环境配置
spring:
  profiles: prod
#  datasource:
#    url: jdbc:mysql://192.168.0.13:3306/